### ISSUE TITLE
[10 + 2 Marks] R5. Design Database Schema + C2. SQL code

### ISSUE THREAD

**Issue by GauravTalreja** [GauravTalreja/ebb#13]
Make sure to run `cargo sqlx prepare --merged` to generate an updated `sqlx-data.json` file.

- [ ]  Update Sample Migrations (fix the course search query if it breaks after the update)
- [ ]  Document assumptions in the report
- [ ]  Update the E/R diagram
- [ ]  Update the relational data model

# Milestone 2 Report requirements

- **[2 marks]** A list of assumptions that you are making about the data being modelled. 
- **[4 marks]** An E/R diagram for your database design. 
- **[4 marks]** A list of database tables with keys declared (relational data model).

# Code Requirements

- **[2 marks]** **C2. SQL code (create tables, etc)**: Files containing the SQL code used for creating tables, constraints, stored procedures and triggers (if any).
